-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 04:25:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ilhasql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ilhasql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ilhasql` DEFAULT CHARACTER SET latin1 ;
USE `ilhasql` ;

-- -----------------------------------------------------
-- Table `ilhasql`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilhasql`.`cidade` (
  `Nome_Cidade` VARCHAR(255) NOT NULL,
  `Guilda` VARCHAR(45) NULL DEFAULT NULL,
  `Mestre da Guilda` VARCHAR(45) NULL DEFAULT NULL,
  `Quantidade_Habitantes` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Nome_Cidade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ilhasql`.`aventureiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilhasql`.`aventureiro` (
  `cartao_aventureiro` VARCHAR(255) NOT NULL,
  `Nome` VARCHAR(45) NULL DEFAULT NULL,
  `Rank` INT(11) NULL DEFAULT NULL,
  `Classe` VARCHAR(45) NULL DEFAULT NULL,
  `Gold` INT(11) NULL DEFAULT NULL,
  `Nome_Cidade` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`cartao_aventureiro`),
  INDEX `Nome_Cidade` (`Nome_Cidade` ASC) VISIBLE,
  CONSTRAINT `aventureiro_ibfk_1`
    FOREIGN KEY (`Nome_Cidade`)
    REFERENCES `ilhasql`.`cidade` (`Nome_Cidade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `aventureiro` (`cartao_aventureiro`,`nome`,`rank`,`classe`,`gold`,`nome_Cidade`) VALUES ("IBO06TFM4NT","Rhiannon",1,"Paladino",586,"Ganglegoft"),("UAO79LVV6BR","Lacota",8,"Bárbaro",111,"Camerit"),("PDM03SDU8RS","Renee",1,"Feiticeiro",583,"Ganglegoft"),("TDR36CTS5NH","Petra",1,"Mago",745,"SQL City"),("LWQ63RZM5IS","Guy",4,"Paladino",662,"Ganglegoft"),("RUR94LFN1SM","Addison",6,"Paladino",221,"Ganglegoft"),("UDS55FTQ0IC","Calvin",2,"Ladino",273,"Camerit"),("VLQ64OGW8BX","Colton",9,"Bárbaro",777,"Ganglegoft"),("FUO98YIW8LF","Blake",4,"Guerreiro",573,"Camerit"),("WPO83HJN2ND","Ezra",10,"Bárbaro",381,"Ganglegoft");
INSERT INTO `aventureiro` (`cartao_aventureiro`,`nome`,`rank`,`classe`,`gold`,`nome_Cidade`) VALUES ("JBV48OER1XZ","Iona",9,"Feiticeiro",350,"Camerit"),("ZIG53LBK9TC","Nayda",10,"Patrulheiro",693,"Camerit"),("WDZ62FIA8HR","Elvis",10,"Paladino",453,"Camerit"),("YHF51HIX1AN","Linus",6,"Feiticeiro",556,"SQL City"),("EJN41ZAL7YA","Jackson",7,"Paladino",650,"Ganglegoft"),("GBC23JCM1SW","Deacon",1,"Bárbaro",251,"Camerit"),("BXX58NMZ8SV","Jason",5,"Patrulheiro",729,"Camerit"),("SNZ82QAT3SM","Jennifer",6,"Ladino",217,"SQL City"),("GQW14GJP9HT","Kane",8,"Bárbaro",168,"SQL City"),("UJW40EBJ9OI","Noah",1,"Guerreiro",217,"SQL City");
INSERT INTO `aventureiro` (`cartao_aventureiro`,`nome`,`rank`,`classe`,`gold`,`nome_Cidade`) VALUES ("CNI99YSS2NW","Latifah",9,"Paladino",379,"Camerit"),("URS88FSU1ON","Maris",6,"Paladino",746,"Camerit"),("GED72EOT9KY","Julie",6,"Paladino",686,"SQL City"),("HTH38BSC5PV","Priscilla",4,"Bárbaro",520,"SQL City"),("ZQM55YEQ1SD","Hiroko",8,"Feiticeiro",211,"Ganglegoft"),("RCR25XWK5UN","Tara",9,"Mago",720,"SQL City"),("AHV92LIF2AS","Cade",1,"Feiticeiro",356,"Ganglegoft"),("BHA01BEB5MG","Barclay",5,"Feiticeiro",789,"Ganglegoft"),("CIX42VQG5YU","Lucy",5,"Mago",619,"Ganglegoft"),("ZEH36YMM0ZR","Lionel",1,"Feiticeiro",551,"Ganglegoft");
INSERT INTO `aventureiro` (`cartao_aventureiro`,`nome`,`rank`,`classe`,`gold`,`nome_Cidade`) VALUES ("RSQ32AGV4RG","Maya",4,"Patrulheiro",752,"Ganglegoft"),("RAD01UXS5YI","Noah",7,"Bárbaro",347,"Ganglegoft"),("OVP51VWR4CI","Raja",9,"Paladino",649,"SQL City"),("XRR92YGN0TQ","Edan",9,"Guerreiro",361,"SQL City"),("XED41MKF1MD","Guinevere",5,"Clérigo",162,"Ganglegoft"),("WPM55GKK9JD","Maggie",3,"Guerreiro",394,"Ganglegoft"),("HAE68LCF5EQ","Veda",2,"Paladino",573,"Ganglegoft"),("KXD45ISC6JN","Ulla",6,"Ladino",474,"Camerit"),("COG62OFF5HG","Amery",6,"Bárbaro",501,"Camerit"),("QIS09KWN8NQ","Gray",2,"Patrulheiro",108,"SQL City");
INSERT INTO `aventureiro` (`cartao_aventureiro`,`nome`,`rank`,`classe`,`gold`,`nome_Cidade`) VALUES ("GOW70YAH3QV","Farrah",4,"Guerreiro",752,"Ganglegoft"),("ECW83FQM8RG","Quail",4,"Bárbaro",125,"Ganglegoft"),("LNM24IBI1KG","Iola",3,"Bárbaro",226,"Ganglegoft"),("QML77ATS5BR","Grady",1,"Paladino",238,"Camerit"),("AOY89FKZ8FM","Justin",7,"Mago",491,"SQL City"),("HIQ84JKE9UT","Carlos",6,"Clérigo",707,"Camerit"),("OGY07BDJ8FK","Marvin",7,"Clérigo",501,"Ganglegoft"),("ZMR58WWA4VF","Raymond",10,"Paladino",780,"Camerit"),("FYW18QQX7FM","Casey",5,"Clérigo",693,"SQL City"),("FPH30BRK5WT","Stephanie",5,"Feiticeiro",788,"SQL City");
INSERT INTO `aventureiro` (`cartao_aventureiro`,`nome`,`rank`,`classe`,`gold`,`nome_Cidade`) VALUES ("BHK08ITH0JK","Haley",1,"Ladino",271,"SQL City"),("MLA30CFN2UK","Jordan",9,"Patrulheiro",732,"SQL City"),("IYQ22MAB1YB","Joseph",6,"Feiticeiro",635,"Camerit"),("HVV80NNJ6ZI","Gail",4,"Paladino",310,"SQL City"),("QQB97LSE4KB","Ava",1,"Ladino",736,"Camerit"),("DOZ31DIV3ZS","Vaughan",9,"Bárbaro",268,"SQL City"),("XDQ22HUL8FT","Keith",10,"Feiticeiro",672,"SQL City"),("XVG33LVE8ZM","Blair",4,"Mago",428,"Camerit"),("QDW96TCL3UQ","Caleb",2,"Mago",603,"Camerit"),("IAQ42AZZ0GW","Clare",1,"Bárbaro",652,"Ganglegoft");
INSERT INTO `aventureiro` (`cartao_aventureiro`,`nome`,`rank`,`classe`,`gold`,`nome_Cidade`) VALUES ("TLG83VHB5BM","Madonna",10,"Bárbaro",578,"Camerit"),("ANO22BTX9CK","Dillon",8,"Patrulheiro",424,"Ganglegoft"),("ZEM99CST6YD","Rhoda",1,"Clérigo",438,"Camerit"),("YMY21VPX4WN","Tana",6,"Ladino",242,"Ganglegoft"),("XHD30SOL6CU","Colleen",9,"Bárbaro",115,"Ganglegoft"),("ZQF20DUL7WY","Ezra",8,"Clérigo",772,"SQL City"),("URQ22WHR1BQ","Deanna",10,"Ladino",424,"Camerit"),("NFP27WAY3TJ","Benjamin",1,"Guerreiro",134,"Camerit"),("EOP72LQQ5MM","Bryar",3,"Patrulheiro",119,"Ganglegoft"),("CMI84ZLE3AK","Gil",6,"Clérigo",563,"Camerit");
INSERT INTO `aventureiro` (`cartao_aventureiro`,`nome`,`rank`,`classe`,`gold`,`nome_Cidade`) VALUES ("DMO66XJZ4EK","Mohammad",2,"Bárbaro",125,"Ganglegoft"),("PCA28CQP4VQ","Mercedes",5,"Clérigo",294,"Camerit"),("OXJ79LYZ2OS","Bertha",7,"Guerreiro",399,"Ganglegoft"),("HXD24OPM3XH","Caesar",10,"Paladino",633,"Ganglegoft"),("DGV72EUD3KY","Lawrence",4,"Mago",148,"Ganglegoft"),("RMH87ONM2MB","Orlando",1,"Guerreiro",589,"SQL City"),("WYO96FSY8YK","Nichole",7,"Bárbaro",191,"SQL City"),("LAI16KNX3OW","Tarik",10,"Mago",432,"SQL City"),("JKH39JUK8NK","Mannix",2,"Bárbaro",302,"Ganglegoft"),("PGE18LEU1DQ","Carson",5,"Clérigo",711,"Ganglegoft");
INSERT INTO `aventureiro` (`cartao_aventureiro`,`nome`,`rank`,`classe`,`gold`,`nome_Cidade`) VALUES ("IKR40YUB2QF","Ruby",6,"Bárbaro",305,"SQL City"),("SYM96NXL9HU","Nicholas",7,"Patrulheiro",615,"Camerit"),("DWI70MUJ2BK","Isabelle",5,"Bárbaro",194,"Camerit"),("RPU82GGE0WZ","Moana",4,"Bárbaro",513,"Ganglegoft"),("AOY89DUM5BO","Maggy",8,"Paladino",474,"Camerit"),("UVC78TSC7LQ","Yuli",2,"Guerreiro",223,"Ganglegoft"),("KWC16XXD9FI","Colorado",6,"Bárbaro",387,"Camerit"),("URB52RAX8JN","Amethyst",8,"Clérigo",591,"SQL City"),("WTE39SWW2YD","Ingrid",4,"Clérigo",451,"SQL City"),("UPN67EJM0GH","Judah",6,"Guerreiro",457,"SQL City");
INSERT INTO `aventureiro` (`cartao_aventureiro`,`nome`,`rank`,`classe`,`gold`,`nome_Cidade`) VALUES ("OSV08WDM7EX","Bryar",5,"Ladino",251,"SQL City"),("TES82XUJ8PZ","Zelda",10,"Feiticeiro",732,"Ganglegoft"),("ZKE84FTI1NP","Rae",6,"Ladino",288,"Ganglegoft"),("XOV92PAQ0IF","Harlan",9,"Feiticeiro",553,"Camerit"),("WJG74PPP8OL","Finn",4,"Mago",294,"SQL City"),("ASH41MQL0HF","Ignacia",7,"Paladino",693,"SQL City"),("OWI06ABL5BC","Lucius",5,"Mago",675,"SQL City"),("DTM38VAA9DN","Lev",3,"Ladino",659,"SQL City"),("YEW07SMF9VF","Dane",8,"Ladino",793,"Camerit"),("RQB93QFB0FC","Grant",10,"Mago",757,"SQL City");

INSERT INTO `cidade` ("Nome_Cidade", "Guilda", "Mestre da Guilda", "quantidade_habitantes") VALUES ("Ganglegoft","Ganglegoft Guild","Ganglegoft Master",12564);
INSERT INTO `cidade` ("Nome_Cidade", "Guilda", "Mestre da Guilda", "quantidade_habitantes") VALUES ("Canerut","Canerut Guild","Canerut Master",8896);
INSERT INTO `cidade` ("Nome_Cidade", "Guilda", "Mestre da Guilda", "quantidade_habitantes") VALUES ("SQL City","SQL Guild","SQL Master",26234);