-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 04:25:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ilhasql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ilhasql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ilhasql` DEFAULT CHARACTER SET latin1 ;
USE `ilhasql` ;

-- -----------------------------------------------------
-- Table `ilhasql`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilhasql`.`cidade` (
  nome_cidade VARCHAR(255) NOT NULL,
  guilda VARCHAR(45) NULL DEFAULT NULL,
  guildmaster VARCHAR(45) NULL DEFAULT NULL,
  quantidade_habitantes INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (nome_cidade))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ilhasql`.`aventureiro`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS aventureiro(
 cartao_aventureiro VARCHAR(255) NOT NULL,
 nome varchar(45) NULL DEFAULT NULL,
 ranque int(2) NULL DEFAULT NULL,
 classe varchar(45) NULL DEFAULT NULL,
 gold int(11) null default null,
 nome_cidade varchar(255) null default null,
 primary key (cartao_aventureiro),
 foreign key aventureiro(nome_cidade) REFERENCES cidade(nome_cidade)
);

CREATE TABLE IF NOT EXISTS COMIDAS(
	nome varchar(255),
    preco int,
    validade int
);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT into COMIDAS (nome, preco, validade) values ("Carne de Vaca", 20, 3);
INSERT into COMIDAS (nome, preco, validade) values ("Carne de Porco", 15, 2);
INSERT into COMIDAS (nome, preco, validade) values ("Repolho", 5, 6);
INSERT into COMIDAS (nome, preco, validade) values ("Cenoura", 6, 7);
INSERT INTO cidade (nome_cidade,guilda, guildmaster, quantidade_Habitantes) VALUES ("SQL City", "SQL Guild", "SQL Master", 21659);
INSERT INTO cidade (nome_cidade,guilda, guildmaster, quantidade_Habitantes) VALUES ("Canerut","Canerut Guild","Canerut Master",8896);
INSERT INTO cidade (nome_cidade,guilda, guildmaster, quantidade_Habitantes) VALUES ("Ganglegoft","Ganglegoft Guild","Ganglegoft Master",12564);
INSERT INTO aventureiro (cartao_aventureiro,nome,ranque,classe,gold,nome_Cidade) VALUES ("IBO06TFM4NT","Rhiannon",1,"Paladino",586,"Ganglegoft"),("UAO79LVV6BR","Lacota",8,"Bárbaro",111,"Camerit");